package com.techchallenge.common;

public interface EventTypes {
	String SUBSCRIPTION_ORDER = "SUBSCRIPTION_ORDER";
	String SUBSCRIPTION_CHANGE = "SUBSCRIPTION_CHANGE";
	String SUBSCRIPTION_CANCEL = "SUBSCRIPTION_CANCEL";
	String SUBSCRIPTION_NOTICE = "SUBSCRIPTION_NOTICE";
	String USER_ASSIGNMENT = "USER_ASSIGNMENT";
	String USER_UNASSIGNMENT = "USER_UNASSIGNMENT";
	String USER_UPDATED = "USER_UPDATED";
	
}
